#!/bin/bash

set -e # exit when any command fails

traingiturl="https://github.com/sem-onyalo"
traingitrepo="gan-training-model"
trainruncmd="python3 main.py"

monitorgiturl="https://github.com/sem-onyalo"
monitorgitrepo="gan-training-monitor-flask"
monitorruncmd="python3 app.py"

function log()
{
  echo [$(date)] "$1"
}

while getopts "tr:tu:tc:mr:mu:mc:" args; do
  case $args in
    tr) traingitrepo=$OPTARG;;
    tu) traingiturl=$OPTARG;;
    tc) trainruncmd=$OPTARG;;
    mr) monitorgitrepo=$OPTARG;;
    mu) monitorgiturl=$OPTARG;;
    mc) monitorruncmd=$OPTARG;;
  esac
done

log 'Creating training bootstrap yaml file'
sed -e "s|{{git-repo}}|$traingitrepo|g" \
    -e "s|{{git-url}}|$traingiturl|g" \
    -e "s|{{run-cmd}}|$trainruncmd|g" \
    bootstrap-template.yml > bootstrap-training.yml

log 'Creating monitoring bootstrap yaml file'
sed -e "s|{{git-repo}}|$monitorgitrepo|g" \
    -e "s|{{git-url}}|$monitorgiturl|g" \
    -e "s|{{run-cmd}}|$monitorruncmd|g" \
    bootstrap-template.yml > bootstrap-monitoring.yml

log 'Validating infrastructure scripts'
terraform validate

log 'Deploying infrastructure'
terraform apply -auto-approve
